### ISSUE TITLE
I installed it but nothing happens.

### ISSUE THREAD

**Issue by tanthammar** [eXolnet/laravel-translation-editor#6]
Not sure on how to use it. From the description it sounds like that there should be some inline editor ?
I can see that there is a blade directive and a middleware. Do I need to publish something?

Please assist :)

**Comment by xel1045** [comment]
I've added a new section in the README.md that explains how to use the plugin: https://github.com/eXolnet/laravel-translation-editor#in-app-translating

Hope it helps.

**Comment by tanthammar** [comment]
Thank you so much, that cleared things up :)
